In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Under-determined | under-constrained

> Minimum length solution for purely under-determined problem.

Solusi dengan lagrange multiplier:
## m = $G^T [GG^T]^{-1}d$

### 3x + 2y = 10

Jika Anda menetapkan x = 2, maka 3(2) + 2y = 10, yang menghasilkan 6 + 2y = 10. Kemudian, y = 2.

Atau, jika Anda menetapkan x = 4, maka 3(4) + 2y = 10, yang menghasilkan 12 + 2y = 10. Kemudian, y = -1.

Ini adalah contoh-contoh solusi yang mungkin untuk persamaan ini dalam kasus inversi under-determined, dan ada banyak solusi lain yang memungkinkan. Jadi, sistem ini memiliki banyak solusi yang memenuhi persamaan tersebut.

In [2]:
# parameter model
x = 2
y = 2
m_obs = np.array([[x,y]])

# d observasi sintetik
d_obs = 3*x + 2*y

# matriks kernel
G = np.array([[3,2]])

# inversi
m_calc = np.transpose(G).dot(np.linalg.inv(G.dot(np.transpose(G)))).dot(d_obs)

print('m observasi:',m_obs)
print('m kalkulasi:',m_calc)

m observasi: [[2 2]]
m kalkulasi: [[2.30769231]
 [1.53846154]]


In [3]:
# testing m kalkulasi
m_calc[0]*3 + m_calc[1]*y

array([10.])

#### Kriteria solusi: $L = m^Tm$

In [4]:
L = np.transpose(m_calc).dot(m_calc)
L

array([[7.69230769]])

### Solusi dengan model referensi
### $m = m_{ref} + G^T[GG^T]^{-1}[d-Gm_{ref}]$

In [5]:
# model referensi
m_ref = np.array([2.1,2.1])

# inversi
m_ref_calc = m_ref + np.transpose(G).dot(np.linalg.inv(G.dot(np.transpose(G)))).dot(d_obs-G.dot(m_ref))
m_ref_calc

array([1.98461538, 2.02307692])

In [6]:
# testing m_ref kalkulasi
m_ref_calc[0]*3 + m_ref_calc[1]*y

10.0

#### Kriteria solusi: $L = [m-m_{ref}]^T[m-m_{ref}]$

In [7]:
L2 = (np.transpose(m_ref_calc-m_ref)).dot(m_ref_calc-m_ref)
L2

0.019230769230769263

In [8]:
L3 = np.transpose(m_ref_calc).dot(m_ref_calc)
L3

8.031538461538462