In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [19]:
s1 = np.array([500,-1000]) # meter
s2 = np.array([1500, -1000]) # meter
s3 = np.array([2000, -750]) # meter
source = np.array([s1, s2, s3])

r1 = np.array([200, 0])

v = np.array([800,1200])

def L_raypath(s,r):
    return np.sqrt((r[0]-s[0])**2 + (r[1]-s[1])**2)

L = np.zeros(3)
for i in range(3):
    L[i] = L_raypath(source[i],r1)
    
G = np.zeros((3,2))
for i in range(1,3):
    for j in range(2):
        G[i,j] = L[i]/2
G[0,0] = L[0]
L

array([1044.03065089, 1640.12194669, 1950.        ])

In [23]:
d= G.dot(1/v)
d 

array([1.30503831, 1.70846036, 2.03125   ])

In [30]:
L[0]/d[0]

800.0

In [32]:
m_calc = np.linalg.inv((G.T).dot(G)).dot(G.T).dot(d)
print(1/m_calc)

[ 800. 1200.]


In [33]:
e = d-G.dot(m_calc)
np.sqrt(e.T.dot(e)/3)

4.440892098500626e-16

In [34]:
d

array([1.30503831, 1.70846036, 2.03125   ])

In [35]:
G.dot(m_calc)

array([1.30503831, 1.70846036, 2.03125   ])