In [1]:
import pandas as pd
import numpy as np

In [2]:
# matriks kernel
G = np.zeros((5,4))
G[0,0] = G[0,1] = 100
G[1,2] = G[1,3] = 100
G[2,0] = G[2,3] = 100*np.sqrt(2)
G[3,1] = G[3,3] = 100
G[4,0] = G[4,2] = 100
G # meter

array([[100.        , 100.        ,   0.        ,   0.        ],
       [  0.        ,   0.        , 100.        , 100.        ],
       [141.42135624,   0.        ,   0.        , 141.42135624],
       [  0.        , 100.        ,   0.        , 100.        ],
       [100.        ,   0.        , 100.        ,   0.        ]])

In [3]:
# kecepatan seismik diketahui, untuk 4 blok secara berurutan
v_obs = np.array([1000,1000,1000,2000]) # m/s

In [4]:
# forward modelling untuk menghasilkan waktu tempuh observasi
t_obs = G.dot(1/v_obs)

In [5]:
# inversi
s_calc = np.linalg.inv((G.T).dot(G)).dot(G.T).dot(t_obs)
v_calc = 1/s_calc
v_calc

array([1000., 1000., 1000., 2000.])

In [6]:
# waktu tempuh observasi 2
t_obs2 = np.array([0.1783, 0.1896, 0.2008, 0.1535, 0.2523])

# inversi ke-2
s_calc2 = np.linalg.inv((G.T).dot(G)).dot(G.T).dot(t_obs2)
v_calc2 = 1/s_calc2
v_calc2

array([1076.79113552, 1053.66884196,  666.86014872, 2035.89192647])

In [7]:
# rmse
e = t_obs2 - G.dot(s_calc2)
rmse = np.sqrt(e.T.dot(e)/5)
rmse # s

0.008474697634724212

In [8]:
rms = np.sqrt(np.sum((t_obs2 - G.dot(s_calc2))**2)/5)
rms

0.008474697634724212